//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Curso2013Turma03Model", "FK_Funcionario_Cargo", "Cargo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Cargo), "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Funcionario), true)]
[assembly: EdmRelationshipAttribute("Curso2013Turma03Model", "FK_Funcionario_Lotacao", "Lotacao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Lotacao), "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Funcionario), true)]
[assembly: EdmRelationshipAttribute("Curso2013Turma03Model", "FK_Funcionario_Municipio", "Municipio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Municipio), "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Funcionario), true)]
[assembly: EdmRelationshipAttribute("Curso2013Turma03Model", "FK_Municipio_UF", "UF", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.UF), "Municipio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model.Municipio), true)]

#endregion

namespace Treinamento2013Curso03.ModelData.Logic.Curso2013Turma03.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Curso2013Turma03Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Curso2013Turma03Entities object using the connection string found in the 'Curso2013Turma03Entities' section of the application configuration file.
        /// </summary>
        public Curso2013Turma03Entities() : base("name=Curso2013Turma03Entities", "Curso2013Turma03Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Curso2013Turma03Entities object.
        /// </summary>
        public Curso2013Turma03Entities(string connectionString) : base(connectionString, "Curso2013Turma03Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Curso2013Turma03Entities object.
        /// </summary>
        public Curso2013Turma03Entities(EntityConnection connection) : base(connection, "Curso2013Turma03Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cargo> Cargoes
        {
            get
            {
                if ((_Cargoes == null))
                {
                    _Cargoes = base.CreateObjectSet<Cargo>("Cargoes");
                }
                return _Cargoes;
            }
        }
        private ObjectSet<Cargo> _Cargoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Funcionario> Funcionarios
        {
            get
            {
                if ((_Funcionarios == null))
                {
                    _Funcionarios = base.CreateObjectSet<Funcionario>("Funcionarios");
                }
                return _Funcionarios;
            }
        }
        private ObjectSet<Funcionario> _Funcionarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lotacao> Lotacaos
        {
            get
            {
                if ((_Lotacaos == null))
                {
                    _Lotacaos = base.CreateObjectSet<Lotacao>("Lotacaos");
                }
                return _Lotacaos;
            }
        }
        private ObjectSet<Lotacao> _Lotacaos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Municipio> Municipios
        {
            get
            {
                if ((_Municipios == null))
                {
                    _Municipios = base.CreateObjectSet<Municipio>("Municipios");
                }
                return _Municipios;
            }
        }
        private ObjectSet<Municipio> _Municipios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UF> UFs
        {
            get
            {
                if ((_UFs == null))
                {
                    _UFs = base.CreateObjectSet<UF>("UFs");
                }
                return _UFs;
            }
        }
        private ObjectSet<UF> _UFs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cargoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCargoes(Cargo cargo)
        {
            base.AddObject("Cargoes", cargo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Funcionarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuncionarios(Funcionario funcionario)
        {
            base.AddObject("Funcionarios", funcionario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lotacaos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLotacaos(Lotacao lotacao)
        {
            base.AddObject("Lotacaos", lotacao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Municipios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMunicipios(Municipio municipio)
        {
            base.AddObject("Municipios", municipio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UFs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUFs(UF uF)
        {
            base.AddObject("UFs", uF);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<PR_ListarFuncionarios_Result> PR_ListarFuncionarios()
        {
            return base.ExecuteFunction<PR_ListarFuncionarios_Result>("PR_ListarFuncionarios");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDCargo">No Metadata Documentation available.</param>
        public ObjectResult<PR_ListarFuncionariosPorCargo_Result> PR_ListarFuncionariosPorCargo(Nullable<global::System.Int32> iDCargo)
        {
            ObjectParameter iDCargoParameter;
            if (iDCargo.HasValue)
            {
                iDCargoParameter = new ObjectParameter("IDCargo", iDCargo);
            }
            else
            {
                iDCargoParameter = new ObjectParameter("IDCargo", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PR_ListarFuncionariosPorCargo_Result>("PR_ListarFuncionariosPorCargo", iDCargoParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDLotacao">No Metadata Documentation available.</param>
        public ObjectResult<PR_ListarFuncionariosPorLotacao_Result> PR_ListarFuncionariosPorLotacao(Nullable<global::System.Int32> iDLotacao)
        {
            ObjectParameter iDLotacaoParameter;
            if (iDLotacao.HasValue)
            {
                iDLotacaoParameter = new ObjectParameter("IDLotacao", iDLotacao);
            }
            else
            {
                iDLotacaoParameter = new ObjectParameter("IDLotacao", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PR_ListarFuncionariosPorLotacao_Result>("PR_ListarFuncionariosPorLotacao", iDLotacaoParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<PR_ListarMunicipios_Result> PR_ListarMunicipios()
        {
            return base.ExecuteFunction<PR_ListarMunicipios_Result>("PR_ListarMunicipios");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="Cargo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cargo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cargo object.
        /// </summary>
        /// <param name="iDCargo">Initial value of the IDCargo property.</param>
        /// <param name="descricaoCargo">Initial value of the DescricaoCargo property.</param>
        public static Cargo CreateCargo(global::System.Int32 iDCargo, global::System.String descricaoCargo)
        {
            Cargo cargo = new Cargo();
            cargo.IDCargo = iDCargo;
            cargo.DescricaoCargo = descricaoCargo;
            return cargo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCargo
        {
            get
            {
                return _IDCargo;
            }
            set
            {
                if (_IDCargo != value)
                {
                    OnIDCargoChanging(value);
                    ReportPropertyChanging("IDCargo");
                    _IDCargo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCargo");
                    OnIDCargoChanged();
                }
            }
        }
        private global::System.Int32 _IDCargo;
        partial void OnIDCargoChanging(global::System.Int32 value);
        partial void OnIDCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoCargo
        {
            get
            {
                return _DescricaoCargo;
            }
            set
            {
                OnDescricaoCargoChanging(value);
                ReportPropertyChanging("DescricaoCargo");
                _DescricaoCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoCargo");
                OnDescricaoCargoChanged();
            }
        }
        private global::System.String _DescricaoCargo;
        partial void OnDescricaoCargoChanging(global::System.String value);
        partial void OnDescricaoCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Cargo", "Funcionario")]
        public EntityCollection<Funcionario> Funcionarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Funcionario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="cargo">Initial value of the Cargo property.</param>
        /// <param name="lotacao">Initial value of the Lotacao property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nome, global::System.String sobrenome, global::System.String cargo, global::System.String lotacao, global::System.String telefone)
        {
            Cliente cliente = new Cliente();
            cliente.ID = id;
            cliente.Nome = nome;
            cliente.Sobrenome = sobrenome;
            cliente.Cargo = cargo;
            cliente.Lotacao = lotacao;
            cliente.Telefone = telefone;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cargo
        {
            get
            {
                return _Cargo;
            }
            set
            {
                OnCargoChanging(value);
                ReportPropertyChanging("Cargo");
                _Cargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cargo");
                OnCargoChanged();
            }
        }
        private global::System.String _Cargo;
        partial void OnCargoChanging(global::System.String value);
        partial void OnCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lotacao
        {
            get
            {
                return _Lotacao;
            }
            set
            {
                OnLotacaoChanging(value);
                ReportPropertyChanging("Lotacao");
                _Lotacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lotacao");
                OnLotacaoChanged();
            }
        }
        private global::System.String _Lotacao;
        partial void OnLotacaoChanging(global::System.String value);
        partial void OnLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="Funcionario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Funcionario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Funcionario object.
        /// </summary>
        /// <param name="iDFuncionario">Initial value of the IDFuncionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="iDCargo">Initial value of the IDCargo property.</param>
        /// <param name="iDLotacao">Initial value of the IDLotacao property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        /// <param name="iDMunicipio">Initial value of the IDMunicipio property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static Funcionario CreateFuncionario(global::System.Int32 iDFuncionario, global::System.String nome, global::System.String sobrenome, global::System.Int32 iDCargo, global::System.Int32 iDLotacao, global::System.String endereco, global::System.Int32 iDMunicipio, global::System.String telefone)
        {
            Funcionario funcionario = new Funcionario();
            funcionario.IDFuncionario = iDFuncionario;
            funcionario.Nome = nome;
            funcionario.Sobrenome = sobrenome;
            funcionario.IDCargo = iDCargo;
            funcionario.IDLotacao = iDLotacao;
            funcionario.Endereco = endereco;
            funcionario.IDMunicipio = iDMunicipio;
            funcionario.Telefone = telefone;
            return funcionario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFuncionario
        {
            get
            {
                return _IDFuncionario;
            }
            set
            {
                if (_IDFuncionario != value)
                {
                    OnIDFuncionarioChanging(value);
                    ReportPropertyChanging("IDFuncionario");
                    _IDFuncionario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFuncionario");
                    OnIDFuncionarioChanged();
                }
            }
        }
        private global::System.Int32 _IDFuncionario;
        partial void OnIDFuncionarioChanging(global::System.Int32 value);
        partial void OnIDFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCargo
        {
            get
            {
                return _IDCargo;
            }
            set
            {
                OnIDCargoChanging(value);
                ReportPropertyChanging("IDCargo");
                _IDCargo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCargo");
                OnIDCargoChanged();
            }
        }
        private global::System.Int32 _IDCargo;
        partial void OnIDCargoChanging(global::System.Int32 value);
        partial void OnIDCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDLotacao
        {
            get
            {
                return _IDLotacao;
            }
            set
            {
                OnIDLotacaoChanging(value);
                ReportPropertyChanging("IDLotacao");
                _IDLotacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDLotacao");
                OnIDLotacaoChanged();
            }
        }
        private global::System.Int32 _IDLotacao;
        partial void OnIDLotacaoChanging(global::System.Int32 value);
        partial void OnIDLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMunicipio
        {
            get
            {
                return _IDMunicipio;
            }
            set
            {
                OnIDMunicipioChanging(value);
                ReportPropertyChanging("IDMunicipio");
                _IDMunicipio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDMunicipio");
                OnIDMunicipioChanged();
            }
        }
        private global::System.Int32 _IDMunicipio;
        partial void OnIDMunicipioChanging(global::System.Int32 value);
        partial void OnIDMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Cargo", "Cargo")]
        public Cargo Cargo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Cargo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Cargo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cargo> CargoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Cargo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cargo>("Curso2013Turma03Model.FK_Funcionario_Cargo", "Cargo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Lotacao", "Lotacao")]
        public Lotacao Lotacao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lotacao>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Lotacao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lotacao>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Lotacao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lotacao> LotacaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lotacao>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Lotacao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lotacao>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Lotacao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Municipio", "Municipio")]
        public Municipio Municipio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipio>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Municipio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipio>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Municipio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Municipio> MunicipioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Municipio>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Municipio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Municipio>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Municipio", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="Lotacao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lotacao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lotacao object.
        /// </summary>
        /// <param name="iDLotacao">Initial value of the IDLotacao property.</param>
        /// <param name="descricaoLotacao">Initial value of the DescricaoLotacao property.</param>
        public static Lotacao CreateLotacao(global::System.Int32 iDLotacao, global::System.String descricaoLotacao)
        {
            Lotacao lotacao = new Lotacao();
            lotacao.IDLotacao = iDLotacao;
            lotacao.DescricaoLotacao = descricaoLotacao;
            return lotacao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDLotacao
        {
            get
            {
                return _IDLotacao;
            }
            set
            {
                if (_IDLotacao != value)
                {
                    OnIDLotacaoChanging(value);
                    ReportPropertyChanging("IDLotacao");
                    _IDLotacao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDLotacao");
                    OnIDLotacaoChanged();
                }
            }
        }
        private global::System.Int32 _IDLotacao;
        partial void OnIDLotacaoChanging(global::System.Int32 value);
        partial void OnIDLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoLotacao
        {
            get
            {
                return _DescricaoLotacao;
            }
            set
            {
                OnDescricaoLotacaoChanging(value);
                ReportPropertyChanging("DescricaoLotacao");
                _DescricaoLotacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoLotacao");
                OnDescricaoLotacaoChanged();
            }
        }
        private global::System.String _DescricaoLotacao;
        partial void OnDescricaoLotacaoChanging(global::System.String value);
        partial void OnDescricaoLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Lotacao", "Funcionario")]
        public EntityCollection<Funcionario> Funcionarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Lotacao", "Funcionario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="Municipio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Municipio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Municipio object.
        /// </summary>
        /// <param name="iDMunicipio">Initial value of the IDMunicipio property.</param>
        /// <param name="descricaoMunicipio">Initial value of the DescricaoMunicipio property.</param>
        /// <param name="iDUF">Initial value of the IDUF property.</param>
        public static Municipio CreateMunicipio(global::System.Int32 iDMunicipio, global::System.String descricaoMunicipio, global::System.Int32 iDUF)
        {
            Municipio municipio = new Municipio();
            municipio.IDMunicipio = iDMunicipio;
            municipio.DescricaoMunicipio = descricaoMunicipio;
            municipio.IDUF = iDUF;
            return municipio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMunicipio
        {
            get
            {
                return _IDMunicipio;
            }
            set
            {
                if (_IDMunicipio != value)
                {
                    OnIDMunicipioChanging(value);
                    ReportPropertyChanging("IDMunicipio");
                    _IDMunicipio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDMunicipio");
                    OnIDMunicipioChanged();
                }
            }
        }
        private global::System.Int32 _IDMunicipio;
        partial void OnIDMunicipioChanging(global::System.Int32 value);
        partial void OnIDMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoMunicipio
        {
            get
            {
                return _DescricaoMunicipio;
            }
            set
            {
                OnDescricaoMunicipioChanging(value);
                ReportPropertyChanging("DescricaoMunicipio");
                _DescricaoMunicipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoMunicipio");
                OnDescricaoMunicipioChanged();
            }
        }
        private global::System.String _DescricaoMunicipio;
        partial void OnDescricaoMunicipioChanging(global::System.String value);
        partial void OnDescricaoMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUF
        {
            get
            {
                return _IDUF;
            }
            set
            {
                OnIDUFChanging(value);
                ReportPropertyChanging("IDUF");
                _IDUF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUF");
                OnIDUFChanged();
            }
        }
        private global::System.Int32 _IDUF;
        partial void OnIDUFChanging(global::System.Int32 value);
        partial void OnIDUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Funcionario_Municipio", "Funcionario")]
        public EntityCollection<Funcionario> Funcionarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("Curso2013Turma03Model.FK_Funcionario_Municipio", "Funcionario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Municipio_UF", "UF")]
        public UF UF
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("Curso2013Turma03Model.FK_Municipio_UF", "UF").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("Curso2013Turma03Model.FK_Municipio_UF", "UF").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UF> UFReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("Curso2013Turma03Model.FK_Municipio_UF", "UF");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UF>("Curso2013Turma03Model.FK_Municipio_UF", "UF", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="UF")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UF : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UF object.
        /// </summary>
        /// <param name="iDUF">Initial value of the IDUF property.</param>
        /// <param name="descricaoUF">Initial value of the DescricaoUF property.</param>
        /// <param name="sigla">Initial value of the Sigla property.</param>
        public static UF CreateUF(global::System.Int32 iDUF, global::System.String descricaoUF, global::System.String sigla)
        {
            UF uF = new UF();
            uF.IDUF = iDUF;
            uF.DescricaoUF = descricaoUF;
            uF.Sigla = sigla;
            return uF;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUF
        {
            get
            {
                return _IDUF;
            }
            set
            {
                if (_IDUF != value)
                {
                    OnIDUFChanging(value);
                    ReportPropertyChanging("IDUF");
                    _IDUF = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUF");
                    OnIDUFChanged();
                }
            }
        }
        private global::System.Int32 _IDUF;
        partial void OnIDUFChanging(global::System.Int32 value);
        partial void OnIDUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoUF
        {
            get
            {
                return _DescricaoUF;
            }
            set
            {
                OnDescricaoUFChanging(value);
                ReportPropertyChanging("DescricaoUF");
                _DescricaoUF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoUF");
                OnDescricaoUFChanged();
            }
        }
        private global::System.String _DescricaoUF;
        partial void OnDescricaoUFChanging(global::System.String value);
        partial void OnDescricaoUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInsert
        {
            get
            {
                return _DataInsert;
            }
            set
            {
                OnDataInsertChanging(value);
                ReportPropertyChanging("DataInsert");
                _DataInsert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInsert");
                OnDataInsertChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInsert;
        partial void OnDataInsertChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataUpdate
        {
            get
            {
                return _DataUpdate;
            }
            set
            {
                OnDataUpdateChanging(value);
                ReportPropertyChanging("DataUpdate");
                _DataUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataUpdate");
                OnDataUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataUpdate;
        partial void OnDataUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnDataUpdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Curso2013Turma03Model", "FK_Municipio_UF", "Municipio")]
        public EntityCollection<Municipio> Municipios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Municipio>("Curso2013Turma03Model.FK_Municipio_UF", "Municipio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Municipio>("Curso2013Turma03Model.FK_Municipio_UF", "Municipio", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="PR_ListarFuncionarios_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PR_ListarFuncionarios_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PR_ListarFuncionarios_Result object.
        /// </summary>
        /// <param name="iDFuncionario">Initial value of the IDFuncionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="descricaoCargo">Initial value of the DescricaoCargo property.</param>
        /// <param name="descricaoLotacao">Initial value of the DescricaoLotacao property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        /// <param name="descricaoMunicipio">Initial value of the DescricaoMunicipio property.</param>
        /// <param name="sigla">Initial value of the Sigla property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static PR_ListarFuncionarios_Result CreatePR_ListarFuncionarios_Result(global::System.Int32 iDFuncionario, global::System.String nome, global::System.String sobrenome, global::System.String descricaoCargo, global::System.String descricaoLotacao, global::System.String endereco, global::System.String descricaoMunicipio, global::System.String sigla, global::System.String telefone)
        {
            PR_ListarFuncionarios_Result pR_ListarFuncionarios_Result = new PR_ListarFuncionarios_Result();
            pR_ListarFuncionarios_Result.IDFuncionario = iDFuncionario;
            pR_ListarFuncionarios_Result.Nome = nome;
            pR_ListarFuncionarios_Result.Sobrenome = sobrenome;
            pR_ListarFuncionarios_Result.DescricaoCargo = descricaoCargo;
            pR_ListarFuncionarios_Result.DescricaoLotacao = descricaoLotacao;
            pR_ListarFuncionarios_Result.Endereco = endereco;
            pR_ListarFuncionarios_Result.DescricaoMunicipio = descricaoMunicipio;
            pR_ListarFuncionarios_Result.Sigla = sigla;
            pR_ListarFuncionarios_Result.Telefone = telefone;
            return pR_ListarFuncionarios_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFuncionario
        {
            get
            {
                return _IDFuncionario;
            }
            set
            {
                OnIDFuncionarioChanging(value);
                ReportPropertyChanging("IDFuncionario");
                _IDFuncionario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFuncionario");
                OnIDFuncionarioChanged();
            }
        }
        private global::System.Int32 _IDFuncionario;
        partial void OnIDFuncionarioChanging(global::System.Int32 value);
        partial void OnIDFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoCargo
        {
            get
            {
                return _DescricaoCargo;
            }
            set
            {
                OnDescricaoCargoChanging(value);
                ReportPropertyChanging("DescricaoCargo");
                _DescricaoCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoCargo");
                OnDescricaoCargoChanged();
            }
        }
        private global::System.String _DescricaoCargo;
        partial void OnDescricaoCargoChanging(global::System.String value);
        partial void OnDescricaoCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoLotacao
        {
            get
            {
                return _DescricaoLotacao;
            }
            set
            {
                OnDescricaoLotacaoChanging(value);
                ReportPropertyChanging("DescricaoLotacao");
                _DescricaoLotacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoLotacao");
                OnDescricaoLotacaoChanged();
            }
        }
        private global::System.String _DescricaoLotacao;
        partial void OnDescricaoLotacaoChanging(global::System.String value);
        partial void OnDescricaoLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoMunicipio
        {
            get
            {
                return _DescricaoMunicipio;
            }
            set
            {
                OnDescricaoMunicipioChanging(value);
                ReportPropertyChanging("DescricaoMunicipio");
                _DescricaoMunicipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoMunicipio");
                OnDescricaoMunicipioChanged();
            }
        }
        private global::System.String _DescricaoMunicipio;
        partial void OnDescricaoMunicipioChanging(global::System.String value);
        partial void OnDescricaoMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="PR_ListarFuncionariosPorCargo_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PR_ListarFuncionariosPorCargo_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PR_ListarFuncionariosPorCargo_Result object.
        /// </summary>
        /// <param name="iDFuncionario">Initial value of the IDFuncionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="descricaoCargo">Initial value of the DescricaoCargo property.</param>
        /// <param name="descricaoLotacao">Initial value of the DescricaoLotacao property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        /// <param name="descricaoMunicipio">Initial value of the DescricaoMunicipio property.</param>
        /// <param name="sigla">Initial value of the Sigla property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static PR_ListarFuncionariosPorCargo_Result CreatePR_ListarFuncionariosPorCargo_Result(global::System.Int32 iDFuncionario, global::System.String nome, global::System.String sobrenome, global::System.String descricaoCargo, global::System.String descricaoLotacao, global::System.String endereco, global::System.String descricaoMunicipio, global::System.String sigla, global::System.String telefone)
        {
            PR_ListarFuncionariosPorCargo_Result pR_ListarFuncionariosPorCargo_Result = new PR_ListarFuncionariosPorCargo_Result();
            pR_ListarFuncionariosPorCargo_Result.IDFuncionario = iDFuncionario;
            pR_ListarFuncionariosPorCargo_Result.Nome = nome;
            pR_ListarFuncionariosPorCargo_Result.Sobrenome = sobrenome;
            pR_ListarFuncionariosPorCargo_Result.DescricaoCargo = descricaoCargo;
            pR_ListarFuncionariosPorCargo_Result.DescricaoLotacao = descricaoLotacao;
            pR_ListarFuncionariosPorCargo_Result.Endereco = endereco;
            pR_ListarFuncionariosPorCargo_Result.DescricaoMunicipio = descricaoMunicipio;
            pR_ListarFuncionariosPorCargo_Result.Sigla = sigla;
            pR_ListarFuncionariosPorCargo_Result.Telefone = telefone;
            return pR_ListarFuncionariosPorCargo_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFuncionario
        {
            get
            {
                return _IDFuncionario;
            }
            set
            {
                OnIDFuncionarioChanging(value);
                ReportPropertyChanging("IDFuncionario");
                _IDFuncionario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFuncionario");
                OnIDFuncionarioChanged();
            }
        }
        private global::System.Int32 _IDFuncionario;
        partial void OnIDFuncionarioChanging(global::System.Int32 value);
        partial void OnIDFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoCargo
        {
            get
            {
                return _DescricaoCargo;
            }
            set
            {
                OnDescricaoCargoChanging(value);
                ReportPropertyChanging("DescricaoCargo");
                _DescricaoCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoCargo");
                OnDescricaoCargoChanged();
            }
        }
        private global::System.String _DescricaoCargo;
        partial void OnDescricaoCargoChanging(global::System.String value);
        partial void OnDescricaoCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoLotacao
        {
            get
            {
                return _DescricaoLotacao;
            }
            set
            {
                OnDescricaoLotacaoChanging(value);
                ReportPropertyChanging("DescricaoLotacao");
                _DescricaoLotacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoLotacao");
                OnDescricaoLotacaoChanged();
            }
        }
        private global::System.String _DescricaoLotacao;
        partial void OnDescricaoLotacaoChanging(global::System.String value);
        partial void OnDescricaoLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoMunicipio
        {
            get
            {
                return _DescricaoMunicipio;
            }
            set
            {
                OnDescricaoMunicipioChanging(value);
                ReportPropertyChanging("DescricaoMunicipio");
                _DescricaoMunicipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoMunicipio");
                OnDescricaoMunicipioChanged();
            }
        }
        private global::System.String _DescricaoMunicipio;
        partial void OnDescricaoMunicipioChanging(global::System.String value);
        partial void OnDescricaoMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="PR_ListarFuncionariosPorLotacao_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PR_ListarFuncionariosPorLotacao_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PR_ListarFuncionariosPorLotacao_Result object.
        /// </summary>
        /// <param name="iDFuncionario">Initial value of the IDFuncionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="descricaoCargo">Initial value of the DescricaoCargo property.</param>
        /// <param name="descricaoLotacao">Initial value of the DescricaoLotacao property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        /// <param name="descricaoMunicipio">Initial value of the DescricaoMunicipio property.</param>
        /// <param name="sigla">Initial value of the Sigla property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static PR_ListarFuncionariosPorLotacao_Result CreatePR_ListarFuncionariosPorLotacao_Result(global::System.Int32 iDFuncionario, global::System.String nome, global::System.String sobrenome, global::System.String descricaoCargo, global::System.String descricaoLotacao, global::System.String endereco, global::System.String descricaoMunicipio, global::System.String sigla, global::System.String telefone)
        {
            PR_ListarFuncionariosPorLotacao_Result pR_ListarFuncionariosPorLotacao_Result = new PR_ListarFuncionariosPorLotacao_Result();
            pR_ListarFuncionariosPorLotacao_Result.IDFuncionario = iDFuncionario;
            pR_ListarFuncionariosPorLotacao_Result.Nome = nome;
            pR_ListarFuncionariosPorLotacao_Result.Sobrenome = sobrenome;
            pR_ListarFuncionariosPorLotacao_Result.DescricaoCargo = descricaoCargo;
            pR_ListarFuncionariosPorLotacao_Result.DescricaoLotacao = descricaoLotacao;
            pR_ListarFuncionariosPorLotacao_Result.Endereco = endereco;
            pR_ListarFuncionariosPorLotacao_Result.DescricaoMunicipio = descricaoMunicipio;
            pR_ListarFuncionariosPorLotacao_Result.Sigla = sigla;
            pR_ListarFuncionariosPorLotacao_Result.Telefone = telefone;
            return pR_ListarFuncionariosPorLotacao_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFuncionario
        {
            get
            {
                return _IDFuncionario;
            }
            set
            {
                OnIDFuncionarioChanging(value);
                ReportPropertyChanging("IDFuncionario");
                _IDFuncionario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFuncionario");
                OnIDFuncionarioChanged();
            }
        }
        private global::System.Int32 _IDFuncionario;
        partial void OnIDFuncionarioChanging(global::System.Int32 value);
        partial void OnIDFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoCargo
        {
            get
            {
                return _DescricaoCargo;
            }
            set
            {
                OnDescricaoCargoChanging(value);
                ReportPropertyChanging("DescricaoCargo");
                _DescricaoCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoCargo");
                OnDescricaoCargoChanged();
            }
        }
        private global::System.String _DescricaoCargo;
        partial void OnDescricaoCargoChanging(global::System.String value);
        partial void OnDescricaoCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoLotacao
        {
            get
            {
                return _DescricaoLotacao;
            }
            set
            {
                OnDescricaoLotacaoChanging(value);
                ReportPropertyChanging("DescricaoLotacao");
                _DescricaoLotacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoLotacao");
                OnDescricaoLotacaoChanged();
            }
        }
        private global::System.String _DescricaoLotacao;
        partial void OnDescricaoLotacaoChanging(global::System.String value);
        partial void OnDescricaoLotacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoMunicipio
        {
            get
            {
                return _DescricaoMunicipio;
            }
            set
            {
                OnDescricaoMunicipioChanging(value);
                ReportPropertyChanging("DescricaoMunicipio");
                _DescricaoMunicipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoMunicipio");
                OnDescricaoMunicipioChanged();
            }
        }
        private global::System.String _DescricaoMunicipio;
        partial void OnDescricaoMunicipioChanging(global::System.String value);
        partial void OnDescricaoMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Curso2013Turma03Model", Name="PR_ListarMunicipios_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PR_ListarMunicipios_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PR_ListarMunicipios_Result object.
        /// </summary>
        /// <param name="iDMunicipio">Initial value of the IDMunicipio property.</param>
        /// <param name="descricaoMunicipio">Initial value of the DescricaoMunicipio property.</param>
        /// <param name="sigla">Initial value of the Sigla property.</param>
        public static PR_ListarMunicipios_Result CreatePR_ListarMunicipios_Result(global::System.Int32 iDMunicipio, global::System.String descricaoMunicipio, global::System.String sigla)
        {
            PR_ListarMunicipios_Result pR_ListarMunicipios_Result = new PR_ListarMunicipios_Result();
            pR_ListarMunicipios_Result.IDMunicipio = iDMunicipio;
            pR_ListarMunicipios_Result.DescricaoMunicipio = descricaoMunicipio;
            pR_ListarMunicipios_Result.Sigla = sigla;
            return pR_ListarMunicipios_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMunicipio
        {
            get
            {
                return _IDMunicipio;
            }
            set
            {
                OnIDMunicipioChanging(value);
                ReportPropertyChanging("IDMunicipio");
                _IDMunicipio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDMunicipio");
                OnIDMunicipioChanged();
            }
        }
        private global::System.Int32 _IDMunicipio;
        partial void OnIDMunicipioChanging(global::System.Int32 value);
        partial void OnIDMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescricaoMunicipio
        {
            get
            {
                return _DescricaoMunicipio;
            }
            set
            {
                OnDescricaoMunicipioChanging(value);
                ReportPropertyChanging("DescricaoMunicipio");
                _DescricaoMunicipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescricaoMunicipio");
                OnDescricaoMunicipioChanged();
            }
        }
        private global::System.String _DescricaoMunicipio;
        partial void OnDescricaoMunicipioChanging(global::System.String value);
        partial void OnDescricaoMunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();

        #endregion
    }

    #endregion
    
}
